
import { GradeData } from './types';

export const TEXTBOOK_DATA: GradeData[] = [
  {
    grade: '6',
    name: 'Global Success 6',
    units: [
      { id: 'gs6-u1', name: 'Unit 1: My New School' },
      { id: 'gs6-u2', name: 'Unit 2: My House' },
      { id: 'gs6-u3', name: 'Unit 3: My Friends' },
      { id: 'gs6-u4', name: 'Unit 4: My Neighbourhood' },
      { id: 'gs6-u5', name: 'Unit 5: Natural Wonders of the World' },
      { id: 'gs6-u6', name: 'Unit 6: Our Tet Holiday' },
      { id: 'gs6-term1', name: 'End term 1' },
      { id: 'gs6-u7', name: 'Unit 7: Television' },
      { id: 'gs6-u8', name: 'Unit 8: Sports and Games' },
      { id: 'gs6-u9', name: 'Unit 9: Cities of the World' },
      { id: 'gs6-u10', name: 'Unit 10: Our Houses in the Future' },
      { id: 'gs6-u11', name: 'Unit 11: Our Greener World' },
      { id: 'gs6-u12', name: 'Unit 12: Robots' },
      { id: 'gs6-term2', name: 'End term 2' },
    ],
  },
  {
    grade: '7',
    name: 'Global Success 7',
    units: [
      { id: 'gs7-u1', name: 'Unit 1: Hobbies' },
      { id: 'gs7-u2', name: 'Unit 2: Health' },
      { id: 'gs7-u3', name: 'Unit 3: Community Service' },
      { id: 'gs7-u4', name: 'Unit 4: Music and Arts' },
      { id: 'gs7-u5', name: 'Unit 5: Vietnamese Food and Drink' },
      { id: 'gs7-u6', name: 'Unit 6: The First University in Viet Nam' },
      { id: 'gs7-term1', name: 'End term 1' },
      { id: 'gs7-u7', name: 'Unit 7: Traffic' },
      { id: 'gs7-u8', name: 'Unit 8: Films' },
      { id: 'gs7-u9', name: 'Unit 9: Festivals Around the World' },
      { id: 'gs7-u10', name: 'Unit 10: Energy Sources' },
      { id: 'gs7-u11', name: 'Unit 11: Travelling in the Future' },
      { id: 'gs7-u12', name: 'Unit 12: An Unforgettable Trip' },
      { id: 'gs7-term2', name: 'End term 2' },
    ],
  },
  {
    grade: '8',
    name: 'Global Success 8',
    units: [
      { id: 'gs8-u1', name: 'Unit 1: Leisure Activities' },
      { id: 'gs8-u2', name: 'Unit 2: Life in the Countryside' },
      { id: 'gs8-u3', name: 'Unit 3: Peoples of Viet Nam' },
      { id: 'gs8-u4', name: 'Unit 4: Our Customs and Traditions' },
      { id: 'gs8-u5', name: 'Unit 5: Lifestyles' },
      { id: 'gs8-u6', name: 'Unit 6: Folk Tales' },
      { id: 'gs8-term1', name: 'End term 1' },
      { id: 'gs8-u7', name: 'Unit 7: Environmental Protection' },
      { id: 'gs8-u8', name: 'Unit 8: Shopping' },
      { id: 'gs8-u9', name: 'Unit 9: Natural Disasters' },
      { id: 'gs8-u10', name: 'Unit 10: Communication in the Future' },
      { id: 'gs8-u11', name: 'Unit 11: Science and Technology' },
      { id: 'gs8-u12', name: 'Unit 12: Life on Other Planets' },
      { id: 'gs8-term2', name: 'End term 2' },
    ],
  },
  {
    grade: '9',
    name: 'Global Success 9',
    units: [
      { id: 'gs9-u1', name: 'Unit 1: Local Environment' },
      { id: 'gs9-u2', name: 'Unit 2: City Life' },
      { id: 'gs9-u3', name: 'Unit 3: Teen Stress and Pressure' },
      { id: 'gs9-u4', name: 'Unit 4: Life in the Past' },
      { id: 'gs9-u5', name: 'Unit 5: Wonders of Viet Nam' },
      { id: 'gs9-u6', name: 'Unit 6: Viet Nam: Then and Now' },
      { id: 'gs9-term1', name: 'End term 1' },
      { id: 'gs9-u7', name: 'Unit 7: Recipes and Eating Habits' },
      { id: 'gs9-u8', name: 'Unit 8: Tourism' },
      { id: 'gs9-u9', name: 'Unit 9: English in the World' },
      { id: 'gs9-u10', name: 'Unit 10: Space Travel' },
      { id: 'gs9-u11', name: 'Unit 11: Changing Roles in Society' },
      { id: 'gs9-u12', name: 'Unit 12: My Future Career' },
      { id: 'gs9-term2', name: 'End term 2' },
    ],
  },
];